Feature/automated docker release
ga4gh/ga4gh-starter-kit-common pull request #42
Opened 2022-01-26 19:31 UTC by emre-f

Created a separate workflow file which is only to be triggered when there is a push happening in main (which will only happen when a PR is being merged from develop).

In this workflow, a docker image will be released with the correct tag.

2022-01-28 16:15 UTC, jb-adams requested changes
`releases.yml` looks like it duplicates a lot of steps from `tests.yml`, like all the unit and docker testing. We want the release step to be dependent on unit and docker tests passing, but not for them to run twice.

Maybe it's best to put everything back into one file? And have a distinct `Docker-Release` job that `needs` `Docker-Integration-Test` to pass.

You could do something like:
```
jobs:
    ...
    Docker-Release:
        if: # expression to run when there's a merge into main
```

See the Github Actions docs for [jobs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs) and [expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)

2022-02-08 15:09 UTC, jb-adams reviewed
Looks good @emre-f , have you tested that the `Docker-Release` successfully pushes to the docker registry?

2022-02-08 15:36 UTC, emre-f commented
I just ran the tests without the main condition, and instead of a docker image with the tag test, the one with tag 0.5.7 was updated.

2022-02-08 18:23 UTC, jb-adams approved these changes

2022-02-08 18:23 UTC, merged